# Generated by Django 3.0.3 on 2022-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userentreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprisepromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Running', models.BooleanField(default=False)),
                ('datePE', models.DateField(null=True)),
                ('nbDays', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('entreprisePE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userentreprise.Userentreprise')),
            ],
        ),
    ]
