# Generated by Django 3.0.3 on 2022-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentNo', models.CharField(blank=True, max_length=200, null=True)),
                ('seenNo', models.BooleanField(default=False)),
                ('dateNo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
