# Generated by Django 3.0.3 on 2022-03-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20220323_2058'),
        ('service', '0004_auto_20220323_2058'),
        ('notifications', '0005_auto_20220323_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='contentNo',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='seenNo',
            new_name='seen',
        ),
        migrations.AddField(
            model_name='notifications',
            name='commentNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='serviceNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
