# Generated by Django 3.0.3 on 2022-03-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0003_auto_20220323_2058'),
        ('notifications', '0006_auto_20220324_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='entrepriseNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userentreprise.Userentreprise'),
        ),
    ]
