# Generated by Django 3.0.3 on 2022-03-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notifications_profileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='commentNo',
        ),
    ]
