# Generated by Django 3.0.3 on 2022-03-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20220323_2058'),
        ('notifications', '0009_remove_notifications_commentno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='byuserprofileNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofiledoneit', to='userprofile.Userprofile'),
        ),
    ]
