# Generated by Django 3.0.3 on 2022-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20220330_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='profileNo',
        ),
    ]
