# Generated by Django 3.0.3 on 2022-03-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_notifications_foradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='promotionnotif',
            field=models.BooleanField(default=False),
        ),
    ]
