# Generated by Django 3.0.3 on 2022-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_notifications_promotionnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='verifnotif',
            field=models.BooleanField(default=False),
        ),
    ]
