# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('question', '0001_initial'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteup', models.BooleanField(default=False)),
                ('votedown', models.BooleanField(default=False)),
                ('dateCreationVo', models.DateTimeField(auto_now_add=True)),
                ('questionVo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('replyVo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reply.Reply')),
                ('userprofileVo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile')),
            ],
        ),
    ]
