# Generated by Django 4.0.1 on 2022-03-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_vote_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voteup',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='votedown',
        ),
    ]
