# Generated by Django 3.0.3 on 2022-03-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20220305_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='replyVo',
        ),
    ]
