# Generated by Django 3.0.3 on 2022-03-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0011_reply_checked'),
        ('vote', '0011_auto_20220307_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='replyVo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reply.Reply'),
        ),
    ]
