# Generated by Django 4.0.1 on 2022-03-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_accepted'),
        ('postgroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='groupPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
