# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('servicetype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleS', models.CharField(blank=True, max_length=200, null=True)),
                ('priceS', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contactS', models.CharField(blank=True, max_length=200, null=True)),
                ('adresseS', models.CharField(blank=True, max_length=200, null=True)),
                ('dateS', models.DateTimeField(auto_now=True)),
                ('imageS', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('evaluationS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Evaluation')),
                ('typeS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicetype.Servicetype')),
                ('userprofileS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile')),
            ],
        ),
    ]
