# Generated by Django 4.0.1 on 2022-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nbvisits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
