# Generated by Django 3.0.3 on 2022-03-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20220312_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='adresseS',
            new_name='addressS',
        ),
    ]
