# Generated by Django 4.0.1 on 2022-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
