# Generated by Django 4.0.1 on 2022-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_service_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
