# Generated by Django 3.0.3 on 2022-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20220313_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
