# Generated by Django 4.0.1 on 2022-03-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_service_id'),
        ('service', '0019_auto_20220313_2143'),
    ]

    operations = [
    ]
