# Generated by Django 4.0.1 on 2022-03-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_merge_0019_alter_service_id_0019_auto_20220313_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nbEval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
