# Generated by Django 4.0.1 on 2022-03-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_service_id'),
        ('service', '0023_auto_20220315_1607'),
    ]

    operations = [
    ]
