# Generated by Django 3.0.3 on 2022-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20220315_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
