# Generated by Django 4.0.1 on 2022-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_merge_0023_alter_service_id_0023_auto_20220315_1607'),
        ('service', '0024_service_promoted'),
    ]

    operations = [
    ]
