# Generated by Django 3.0.3 on 2022-02-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='contenuRec',
            new_name='contentRec',
        ),
        migrations.RenameField(
            model_name='reclamation',
            old_name='titreRec',
            new_name='titleRec',
        ),
    ]
