# Generated by Django 4.0.1 on 2022-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0002_alter_reclamation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='contentRec',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='titleRec',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='userprofileRec',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='emailRec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='messageRec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nameRec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='telRec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='dateRec',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
