# Generated by Django 3.0.3 on 2022-03-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0013_auto_20220309_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorC', models.CharField(blank=True, max_length=200, null=True)),
                ('dateCreationC', models.DateTimeField(auto_now_add=True)),
                ('imageC', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('userprofileC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile')),
            ],
        ),
    ]
