# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('carenergy', '0001_initial'),
        ('carmodele', '0001_initial'),
        ('carengine', '0001_initial'),
        ('cartype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorC', models.CharField(blank=True, max_length=200, null=True)),
                ('dateCreationC', models.DateTimeField(auto_now_add=True)),
                ('imageC', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brandC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('energyC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carenergy.Carenergy')),
                ('engineC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carengine.Carengine')),
                ('modeleC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmodele.Carmodele')),
                ('typeC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartype.Cartype')),
            ],
        ),
    ]
