# Generated by Django 4.0.1 on 2022-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationprofile', '0006_auto_20220326_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationprofile',
            name='commentEval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
