# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentCo', models.TextField(blank=True, null=True)),
                ('dateCo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
