# Generated by Django 4.0.1 on 2022-03-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0009_userentreprise_nbquestions_userentreprise_nbreplies'),
        ('vote', '0006_alter_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='userentrepriseVo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userentreprise.userentreprise'),
        ),
    ]
