# Generated by Django 3.0.3 on 2022-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='preview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
