# Generated by Django 4.0.1 on 2022-03-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_id'),
        ('chat', '0002_chat_preview'),
    ]

    operations = [
    ]
