# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('nbquestions', models.IntegerField(default=0)),
                ('nbreplies', models.IntegerField(default=0)),
                ('nblikes', models.IntegerField(default=0)),
                ('nbvisits', models.IntegerField(default=0)),
                ('dateinscrit', models.DateTimeField(auto_now_add=True)),
                ('imageU', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('badgeU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badge.Badge')),
                ('roleU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
                ('userU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
