# Generated by Django 3.0.3 on 2022-03-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20220302_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adresse',
            new_name='address',
        ),
    ]
