# Generated by Django 4.0.1 on 2022-03-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_id'),
        ('userprofile', '0005_auto_20220302_2324'),
    ]

    operations = [
    ]
