# Generated by Django 4.0.1 on 2022-03-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20220328_2212'),
        ('userprofile', '0008_userprofile_verified'),
    ]

    operations = [
    ]
