# Generated by Django 3.0.3 on 2022-03-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('userprofile', '0013_auto_20220309_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferencesU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.Preferences'),
        ),
    ]
