# Generated by Django 4.0.1 on 2022-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_userprofile_id'),
        ('userprofile', '0014_userprofile_preferencesu'),
    ]

    operations = [
    ]
