# Generated by Django 4.0.1 on 2022-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
