# Generated by Django 3.0.3 on 2022-03-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_auto_20220315_1029'),
        ('userprofile', '0021_userprofile_nbevalprofile'),
    ]

    operations = [
    ]
