# Generated by Django 3.0.3 on 2022-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20220319_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badgeU',
            field=models.IntegerField(default=0),
        ),
    ]
