# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userentreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameE', models.CharField(blank=True, max_length=200, null=True)),
                ('typeE', models.CharField(blank=True, max_length=200, null=True)),
                ('adresseE', models.CharField(blank=True, max_length=200, null=True)),
                ('emailE', models.CharField(blank=True, max_length=200, null=True)),
                ('contactE', models.IntegerField(default=0)),
                ('dateinscritE', models.DateTimeField(auto_now_add=True)),
                ('imageE', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('roleE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
                ('userE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
