# Generated by Django 3.0.3 on 2022-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0006_userentreprise_imageverif'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='nbvisits',
            field=models.IntegerField(default=0),
        ),
    ]
