# Generated by Django 4.0.1 on 2022-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0007_userentreprise_nbvisits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentreprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
