# Generated by Django 4.0.1 on 2022-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0008_alter_userentreprise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='nbquestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userentreprise',
            name='nbreplies',
            field=models.IntegerField(default=0),
        ),
    ]
