# Generated by Django 3.0.3 on 2022-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0019_auto_20220318_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentreprise',
            name='emailE',
        ),
        migrations.AddField(
            model_name='userentreprise',
            name='nbEval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
