# Generated by Django 3.0.3 on 2022-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0020_auto_20220318_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentreprise',
            name='nbEval',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
