# Generated by Django 3.0.3 on 2022-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0021_auto_20220318_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
