# Generated by Django 3.0.3 on 2022-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0022_userentreprise_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userentreprise',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
