# Generated by Django 4.0.1 on 2022-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
