# Generated by Django 3.0.3 on 2022-04-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0002_auto_20220401_1002'),
        ('groupmember', '0002_groupmember_accepted'),
    ]

    operations = [
    ]
