# Generated by Django 3.0.3 on 2022-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicepromotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepromotion',
            name='dateP',
            field=models.DateTimeField(null=True),
        ),
    ]
