# Generated by Django 3.0.3 on 2022-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicepromotion', '0002_auto_20220318_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepromotion',
            name='dateP',
            field=models.DateField(null=True),
        ),
    ]
