# Generated by Django 4.0.1 on 2022-03-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationprofile', '0002_auto_20220315_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
