# Generated by Django 4.0.1 on 2022-03-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0005_auto_20220326_2211'),
        ('questioncategory', '0005_questioncategory_imagecat'),
    ]

    operations = [
    ]
