# Generated by Django 4.0.1 on 2022-03-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0007_alter_reply_id'),
        ('reply', '0007_reply_userentrepriserep'),
    ]

    operations = [
    ]
