# Generated by Django 4.0.1 on 2022-03-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0012_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleG', models.CharField(blank=True, max_length=200, null=True)),
                ('nbposts', models.IntegerField(default=0)),
                ('nbmembers', models.IntegerField(default=0)),
                ('dateinscrit', models.DateTimeField(auto_now_add=True)),
                ('imageG', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('userprofileG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
        ),
    ]
