# Generated by Django 4.0.1 on 2022-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='countryG',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
