# Generated by Django 4.0.1 on 2022-03-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_id'),
        ('service', '0007_service_userentreprises'),
    ]

    operations = [
    ]
