# Generated by Django 3.0.3 on 2022-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentreprise', '0005_auto_20220326_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='imageVerif',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
