# Generated by Django 4.0.1 on 2022-03-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0004_alter_questioncategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='imageCat',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
