# Generated by Django 4.0.1 on 2022-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0006_merge_20220327_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
