# Generated by Django 4.0.1 on 2022-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0014_auto_20220403_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
