# Generated by Django 4.0.1 on 2022-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationentreprise', '0010_alter_evaluationentreprise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationentreprise',
            name='commentEval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
