# Generated by Django 4.0.1 on 2022-03-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_userprofile_id'),
        ('userprofile', '0006_userprofile_imageverif'),
    ]

    operations = [
    ]
