# Generated by Django 4.0.1 on 2022-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_countryg'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
