# Generated by Django 3.0.3 on 2022-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentR', models.TextField(blank=True, null=True)),
                ('nblikesR', models.IntegerField(default=0)),
                ('nbCommentR', models.IntegerField(default=0)),
                ('dateR', models.DateTimeField(auto_now_add=True)),
                ('imageR', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('checked', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=False)),
                ('questionRep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('userprofileRep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile')),
            ],
        ),
    ]
