# Generated by Django 3.0.3 on 2022-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_initial'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='voteRep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Vote'),
        ),
    ]
