# Generated by Django 3.0.3 on 2022-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0010_auto_20220307_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
