# Generated by Django 3.0.3 on 2022-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0013_auto_20220309_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
