# Generated by Django 3.0.3 on 2022-03-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0014_reply_accepted'),
        ('reply', '0014_alter_reply_id'),
    ]

    operations = [
    ]
