# Generated by Django 3.0.3 on 2022-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
