# Generated by Django 4.0.1 on 2022-04-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0002_auto_20220401_1002'),
        ('groupmember', '0002_groupmember_accepted'),
    ]

    operations = [
    ]
