# Generated by Django 4.0.1 on 2022-04-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0003_merge_20220401_2043'),
        ('groupmember', '0003_merge_20220401_2150'),
    ]

    operations = [
    ]
