# Generated by Django 3.0.3 on 2022-04-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0003_merge_20220401_2150'),
        ('groupmember', '0003_merge_20220401_2043'),
    ]

    operations = [
    ]
