# Generated by Django 4.0.1 on 2022-04-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmember', '0004_merge_20220402_1218'),
        ('groupmember', '0004_merge_20220402_1313'),
    ]

    operations = [
    ]
