# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questioncategory', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandPref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('categoryPref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioncategory.Questioncategory')),
            ],
        ),
    ]
