# Generated by Django 3.0.3 on 2022-03-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0005_auto_20220303_2041'),
        ('userprofile', '0007_auto_20220303_2041'),
        ('brand', '0005_auto_20220303_2041'),
        ('preferences', '0005_alter_preferences_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='brandPref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='categoryPref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questioncategory.Questioncategory'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='userprofilePref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile'),
        ),
    ]
