# Generated by Django 4.0.1 on 2022-04-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0012_alter_userprofile_id'),
        ('postgroup', '0002_postgroup_grouppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentCom', models.CharField(blank=True, max_length=200, null=True)),
                ('dateinscrit', models.DateTimeField(auto_now_add=True)),
                ('postCom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postgroup.postgroup')),
                ('userprofileCom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
        ),
    ]
