# Generated by Django 3.0.3 on 2022-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_remove_reclamation_contentrec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
