# Generated by Django 3.0.3 on 2022-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0014_auto_20220403_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='nameRec',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
