# Generated by Django 3.0.3 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questioncategory', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleQ', models.CharField(blank=True, max_length=200, null=True)),
                ('contentQ', models.TextField(blank=True, null=True, unique=True)),
                ('nblikes', models.IntegerField(default=0)),
                ('nbrep', models.IntegerField(default=0)),
                ('dateQ', models.DateTimeField(auto_now_add=True)),
                ('imageQ', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categoryQ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questioncategory.Questioncategory')),
                ('userprofileQ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile')),
            ],
        ),
    ]
