# Generated by Django 4.0.1 on 2022-03-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
