# Generated by Django 4.0.1 on 2022-03-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20220303_2041'),
        ('question', '0006_question_accepted_question_pending'),
    ]

    operations = [
    ]
