# Generated by Django 4.0.1 on 2022-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_merge_20220304_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pending',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
