# Generated by Django 3.0.3 on 2022-04-03 00:38

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20220403_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['titleQ']),
        ),
    ]
