# Generated by Django 3.0.3 on 2022-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='titleQ',
            field=models.CharField(blank=True, max_length=501, null=True, unique=True),
        ),
    ]
