# Generated by Django 4.0.1 on 2022-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
