# Generated by Django 3.0.3 on 2022-03-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0025_auto_20220319_1057'),
        ('question', '0025_question_modified'),
    ]

    operations = [
    ]
