# Generated by Django 3.0.3 on 2022-03-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20220323_2058'),
        ('notifications', '0007_auto_20220324_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='profileNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userprofile.Userprofile'),
        ),
    ]
