# Generated by Django 3.0.3 on 2022-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_remove_notifications_profileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='foradmin',
            field=models.BooleanField(default=False),
        ),
    ]
