# Generated by Django 3.0.3 on 2022-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20220403_0123'),
        ('notifications', '0025_auto_20220403_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='groupNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
    ]
